version: "2"
services:
  
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"

  web:
    container_name: python_app
    build: .
    command: python test.py
    links:
      - chrome
