version: "3"
services:

#
#  selenium-hub:
#    restart: always
#    image: selenium/hub:3.14.0
#    container_name: selenium-hub
#    ports:
#      - "4444:4444"

  chrome:
#    restart: always
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"
#    depends_on:
#      - selenium-hub
#    environment:
#      HUB_HOST: selenium-hub
#      HUB_PORT_4444_TCP_ADDR: selenium-hub
#      HUB_PORT_4444_TCP_PORT: 4444
#      DBUS_SESSION_BUS_ADDRESS: "/dev/null"
#    links:
#      - selenium-hub:hub

  web:
    container_name: python_app
    build: .
    command: python test.py
    links:
      - chrome