version: "3"
services:

  firefox:
    image: selenium/standalone-firefox
    ports:
      - "4446:4444"



  web:
    container_name: python_app
    build: .
    command: python parsing_service.py
    links:
      - firefox